services:
  db:
    image: postgres:15
    restart: always
    networks:
      - smartpay-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: smartpay
      POSTGRES_USER: smartpay
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  payment-db:
    image: postgres:15
    restart: always
    networks:
      - smartpay-network
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: smartpay_payments
      POSTGRES_USER: smartpay
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"
  redis:
    image: redis:7
    networks:
      - smartpay-network
    ports:
      - "6379:6379"
    restart: always
volumes:
  postgres_data:
  payment_postgres_data:
networks:
  smartpay-network:
    driver: bridge